export const teachers = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "英语教师",
    image: "/images/Sarah Johnson.png",
    nationality: "英国",
    education: "剑桥大学英语教育硕士",
    experience: "10年教学经验",
    description: "专注商务英语和雅思培训，曾帮助数百名学员成功提升英语水平。",
  },
  {
    id: 2,
    name: "李梦",
    role: "英语教师",
    image: "/images/limeng.png",
    nationality: "中国",
    education: "西安外国语大学英语语言文学硕士",
    experience: "8年教学经验",
    description: "专注英语考试培训，擅长英语语法教学和写作指导，教学方法灵活多样。",
  },
  {
    id: 3,
    name: "Marie Dubois",
    role: "法语教师",
    image: "/images/Marie Dubois.png",
    nationality: "法国",
    education: "巴黎索邦大学法语教育学士",
    experience: "8年教学经验",
    description: "专注法语考试培训，教学风格活泼，深受学员喜爱。",
  },
  {
    id: 4,
    name: "王晓华",
    role: "法语教师",
    image: "/images/wangxiaohua.png",
    nationality: "中国",
    education: "法国里昂第三大学法语语言文学硕士",
    experience: "6年教学经验",
    description: "有丰富的法语教学经验，擅长零基础教学，注重实用交际能力的培养。",
  },
  {
    id: 5,
    name: "田中雅子",
    role: "日语教师",
    image: "/images/tianzhongyazi.png",
    nationality: "日本",
    education: "早稻田大学日本语教育硕士",
    experience: "12年教学经验",
    description: "擅长日语零基础教学和N1备考，教学经验丰富。",
  },
  {
    id: 6,
    name: "赵雪",
    role: "日语教师",
    image: "/images/zhaoxue.png",
    nationality: "中国",
    education: "东北师范大学日语语言文学硕士",
    experience: "7年教学经验",
    description: "精通日语教学方法，擅长语法讲解和应试技巧指导。",
  },
  {
    id: 7,
    name: "Michael Schmidt",
    role: "德语教师",
    image: "/images/Michael Schmidt.png",
    nationality: "德国",
    education: "柏林自由大学德语教育博士",
    experience: "15年教学经验",
    description: "专注德语教学和留学指导，帮助众多学员成功留学德国。",
  },
  {
    id: 8,
    name: "陈静",
    role: "德语教师",
    image: "/images/chenjing.png",
    nationality: "中国",
    education: "德国慕尼黑大学德语语言文学硕士",
    experience: "5年教学经验",
    description: "有海外留学背景，擅长德语考试培训和文化课程教学。",
  },
  {
    id: 9,
    name: "张明",
    role: "IT技术讲师",
    image: "/images/zhangming.png",
    nationality: "中国",
    education: "西安交通大学计算机科学硕士",
    experience: "8年开发经验，5年教学经验",
    description: "全栈开发专家，擅长实战教学，注重培养实际开发能力。",
  },
  {
    id: 10,
    name: "刘涛",
    role: "IT技术讲师",
    image: "/images/liutao.png",
    nationality: "中国",
    education: "西北工业大学软件工程硕士",
    experience: "10年开发经验，4年教学经验",
    description: "前阿里巴巴高级工程师，专注后端开发和架构设计教学。",
  }
]; 